-- Seed properties with data aligned to Airbnb listings
INSERT INTO properties (id, name, location, description, guests, bedrooms, bathrooms, price, category, aesthetic, virtual_tour_url, video_url, images, features, story, testimonials, highlights, created_at, updated_at) VALUES
(1, 'Sky Lounge', 'Worli', 'Luxury penthouse with panoramic city views, featuring 360-degree city views, private terrace, and personalized service. The ultimate luxury experience in Mumbai''s most prestigious neighborhood.', 8, 4, 3, 25000, 'luxury', 'modern', NULL, NULL, '{"Sky Lounge/IMG_1401.jpg", "Sky Lounge/IMG_1405.jpg", "Sky Lounge/IMG_1407.jpg"}', '{"amenities": ["WiFi", "Air Conditioning", "Kitchen", "Terrace", "Pool", "Butler Service"], "rating": 4.9, "reviews_count": 203, "is_available": true}', 'Sky Lounge was created as the ultimate luxury experience in Mumbai. Every element has been thoughtfully designed to provide the highest level of comfort and service, from the 360-degree city views to the personalized butler service. Located in Mumbai''s most prestigious neighborhood, this property offers guests a unique opportunity to experience luxury living at its finest.', '[{"user": "Michael R.", "rating": 5, "comment": "The ultimate luxury experience. The views and service are unmatched.", "date": "2024-01-30"}, {"user": "Priya S.", "rating": 5, "comment": "Absolutely stunning penthouse with incredible city views. Perfect for special occasions.", "date": "2024-01-28"}]', '{"360° City Views", "Luxury Amenities", "Private Terrace", "Exclusive Service"}', '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
(2, 'The Little White Bandra Studio', 'Bandra West', 'Modern white studio in the heart of Bandra, featuring smart layout, contemporary design, and all modern amenities. Perfect for solo travelers, couples, or digital nomads seeking a comfortable base in the heart of Bandra.', 2, 1, 1, 7500, 'studio', 'modern', NULL, NULL, '{"Little White Bandra Studio/IMG_1092.jpg", "Little White Bandra Studio/IMG_1097.jpg", "Little White Bandra Studio/IMG_1101.jpg"}', '{"amenities": ["WiFi", "Air Conditioning", "Kitchen", "Balcony", "Central Location"], "rating": 4.6, "reviews_count": 189, "is_available": true}', 'The Little White Bandra Studio was created as a modern sanctuary for the urban explorer. Every element has been thoughtfully designed to provide comfort and functionality, from the smart layout to the contemporary furnishings. Located in the heart of Bandra West, this property offers guests a unique opportunity to experience Mumbai''s most dynamic neighborhood while enjoying the comforts of modern living.', '[{"user": "Priya M.", "rating": 5, "comment": "Perfect studio for exploring Bandra! The smart layout and prime location made our stay both comfortable and convenient.", "date": "2024-01-25"}, {"user": "Rajesh K.", "rating": 5, "comment": "Great modern studio with all the Bandra vibes. The location is perfect for shopping and exploring the neighborhood.", "date": "2024-01-20"}]', '{"Smart Studio Layout", "Prime Bandra Location", "Modern Amenities", "Bandra Vibes"}', '2024-01-02T00:00:00Z', '2024-01-02T00:00:00Z'),
(3, 'India House', 'Fort', 'Experience the authentic essence of Indian hospitality in this beautifully curated heritage-inspired home. This unique property combines traditional Indian design elements with modern comfort, creating a perfect sanctuary for travelers seeking an immersive cultural experience.', 6, 3, 2, 13500, 'heritage', 'traditional', NULL, NULL, '{"India House/IMG_5220.jpg", "India House/IMG_5222.jpg", "India House/IMG_5224.jpg"}', '{"amenities": ["WiFi", "Air Conditioning", "Kitchen", "Traditional Artwork", "Garden", "Cultural Experience"], "rating": 4.7, "reviews_count": 145, "is_available": true}', 'India House was created as a celebration of India''s rich cultural heritage and traditional hospitality. Every element has been thoughtfully designed to showcase the authentic essence of Indian living, from the handcrafted furniture to the traditional artwork. Located in the historic Fort area, this property offers guests a unique opportunity to experience the cultural heart of Mumbai while enjoying the warmth of traditional Indian hospitality.', '[{"user": "Priya M.", "rating": 5, "comment": "Absolutely magical! The traditional design and cultural elements made our stay truly authentic. Perfect for experiencing Indian hospitality.", "date": "2024-01-25"}, {"user": "Rajesh K.", "rating": 5, "comment": "The heritage charm and traditional artwork created an unforgettable experience. The cultural elements made us feel truly connected to India.", "date": "2024-01-20"}]', '{"Traditional Indian Design", "Cultural Experience", "Heritage Elements", "Local Artwork"}', '2024-01-03T00:00:00Z', '2024-01-03T00:00:00Z'),
(4, 'City Zen', 'Lower Parel', 'Discover urban tranquility in this beautifully curated zen-inspired suite. This sophisticated retreat combines contemporary design with mindful living, creating the perfect sanctuary for modern travelers seeking balance in the heart of the city.', 3, 1, 1, 11000, 'wellness', 'zen', NULL, NULL, '{"City Zen/00edd2c3-25eb-405d-8280-ffe784337fde.jpg", "City Zen/0a6b040e-5e64-42ad-97c2-0af56b2ab399.jpg", "City Zen/0ccf1b7c-371e-429c-a702-fda2b558f250.jpg"}', '{"amenities": ["WiFi", "Air Conditioning", "Kitchen", "Meditation Space", "City View", "Dedicated Workspace"], "rating": 4.8, "reviews_count": 167, "is_available": true}', 'City Zen was created as a modern sanctuary for the urban professional. Every element has been thoughtfully designed to promote both productivity and wellness, from the dedicated workspace to the meditation corner. Located in the heart of Mumbai''s business district, this property offers guests a unique opportunity to experience tranquility while staying connected to the city''s vibrant energy.', '[{"user": "Priya M.", "rating": 5, "comment": "Perfect blend of work and wellness! The meditation corner and city views created the ideal environment for both productivity and relaxation.", "date": "2024-01-25"}, {"user": "Rajesh K.", "rating": 5, "comment": "The zen atmosphere helped me stay focused during my business trip. The modern amenities and peaceful design are exactly what I needed.", "date": "2024-01-20"}]', '{"Dedicated Meditation Corner", "City Views", "Natural Materials", "Modern Design"}', '2024-01-04T00:00:00Z', '2024-01-04T00:00:00Z'),
(5, 'Bandra Cottage', 'Bandra West', 'A charming cottage nestled in the heart of Bandra, offering a perfect blend of comfort and character. This unique property combines cozy design with modern amenities, creating an ideal sanctuary for travelers seeking an authentic Bandra experience.', 4, 2, 1, 8500, 'cottage', 'charming', NULL, NULL, '{"Photos Bandra Cottage/IMG_7268.jpg", "Photos Bandra Cottage/IMG_7273.jpg", "Photos Bandra Cottage/IMG_7276.jpg"}', '{"amenities": ["WiFi", "Air Conditioning", "Kitchen", "Balcony", "Garden", "Comfortable Living"], "rating": 4.8, "reviews_count": 156, "is_available": true}', 'Bandra Cottage was created as a charming retreat in the heart of Bandra. Every element has been thoughtfully designed to provide comfort and character, from the cozy furnishings to the peaceful garden. Located in the heart of Bandra West, this property offers guests a unique opportunity to experience the authentic charm of Mumbai''s most beloved neighborhood.', '[{"user": "Priya M.", "rating": 5, "comment": "Charming cottage in the perfect location! The comfort and Bandra charm made our stay unforgettable.", "date": "2024-01-25"}, {"user": "Rajesh K.", "rating": 5, "comment": "Great cottage with all the comforts. The location is perfect for exploring Bandra.", "date": "2024-01-20"}]', '{"Charming Design", "Prime Location", "Comfortable Stay", "Bandra Charm"}', '2024-01-05T00:00:00Z', '2024-01-05T00:00:00Z'),
(6, 'The Bandra Art House', 'Bandra West', 'Experience the vibrant artistic culture of Bandra in this beautifully curated art house. This unique space combines contemporary design with local artistic flair, featuring original artwork, a creative studio space, and a private balcony with stunning city views.', 4, 2, 1, 8500, 'creative', 'artistic', NULL, NULL, '{"Bandra Art House/IMG_6507.jpg", "Bandra Art House/IMG_6512.jpg", "Bandra Art House/IMG_6518.jpg"}', '{"amenities": ["WiFi", "Air Conditioning", "Kitchen", "Art Studio", "Balcony", "Creative Space"], "rating": 4.8, "reviews_count": 156, "is_available": true}', 'The Bandra Art House was created as a celebration of Mumbai''s vibrant artistic community. Every piece of artwork tells a story of the city''s rich cultural heritage, while the space itself serves as both a comfortable home and an inspiring creative sanctuary. Located in the heart of Bandra''s artistic district, this property offers guests a unique opportunity to immerse themselves in the creative energy that makes this neighborhood so special.', '[{"user": "Sarah M.", "rating": 5, "comment": "Absolutely magical! The artwork and creative energy made our stay unforgettable. Perfect location in Bandra.", "date": "2024-01-15"}, {"user": "Raj K.", "rating": 5, "comment": "Beautiful space with amazing artwork. The balcony views are stunning and the neighborhood is perfect.", "date": "2024-01-10"}]', '{"Original Local Artwork", "Creative Studio Space", "Private Balcony", "Artistic Neighborhood"}', '2024-01-06T00:00:00Z', '2024-01-06T00:00:00Z');

-- Create admin user for property management
INSERT INTO user_profiles (
    phone, full_name, email, role, is_verified, preferences
) VALUES (
    '+91-9876543210',
    'Infiniti Casa Admin',
    'admin@infiniticasa.com',
    'admin',
    true,
    '{"notifications": true, "language": "en"}'
);

-- Create sample newsletter subscription
INSERT INTO newsletter_subscriptions (
    email, phone, full_name, subscription_status, subscription_source
) VALUES (
    'newsletter@infiniticasa.com',
    '+91-9876543210',
    'Infiniti Casa Newsletter',
    'active',
    'system'
);

-- Log the seeding activity
INSERT INTO user_activity_log (
    user_id, activity_type, activity_data
) VALUES (
    (SELECT id FROM user_profiles WHERE phone = '+91-9876543210'),
    'database_seeding',
    '{"properties_added": 8, "admin_created": true, "newsletter_created": true}'
); 